### ISSUE TITLE
obsolete CloseNotifier()

### ISSUE THREAD

**Issue by siredwin** [alexandrevicenzi/go-sse#14] opened 2020-01-12 20:01 UTC
Refer to [echo discussion](https://github.com/labstack/echo/pull/1269).

Consider changing
```go
//closeNotify := response.(http.CloseNotifier).CloseNotify()
closeNotify := request.Context().Done()
```

**Comment by alexandrevicenzi** [comment] 2020-01-13 11:25
Duplicate of #8.

**Closed by alexandrevicenzi** 2020-01-13 11:25 UTC
